### ISSUE TITLE
m-buffer dependency requires Emacs 25?

### ISSUE THREAD

**Issue by alphapapa** [phillord/assess#12]
Hi, I was looking forward to using `assess` to help with testing, but when I try to install it, it fails because the `m-buffer` dependency requires Emacs 25.  Can this requirement be relaxed somehow, or am I going to have to build Emacs 25?  :)

Thanks.

**Comment by phillord** [comment]
Oh, I thought I had fixed that, but apparently not. I will investigate.

**Comment by phillord** [comment]
Funny thing is, I had done all the work to make m-buffer work with Emacs-24 7 months ago, but then never merged it. Turned out to be because I was waiting for a bug fix to seq.el, but that happened ages ago.

I need to let m-buffer percolate. Fingers crossed should be able to do a new release of assess this weekend.

**Comment by alphapapa** [comment]
Sounds great, thanks!

**Comment by phillord** [comment]
Took slightly longer to fix that I though,  but this is complete now. Emacs 24.5,24.4 are not fully supported, and 24.3->24.1 are supported except for the call capturing functionality.

**Comment by alphapapa** [comment]
Thanks!  :)
