### ISSUE TITLE
`make just-test` fails to find m-buffer-at.el

### ISSUE THREAD

**Issue by dunn** [phillord/assess#15]
On macOS 10.12.5:
```
$ make just-test
EMACS=emacs cask emacs --batch -q \
	--directory=. \
	--load assess-discover.el \
	--funcall assess-discover-run-and-exit-batch
Loading /Users/alex/Library/Caches/Homebrew/assess-emacs-0.4/test/assess-call-test.el (source)...
Cannot open load file: No such file or directory, m-buffer-at
make: *** [just-test] Error 255
```
This is after running `cask install`, so presumably m-buffer isn't being installed correctly by Cask.

**Comment by phillord** [comment]
Difficult for me to debug this without further information. As you say, the error comes because m-buffer-at is not being loaded, but whether this is a flaw with assess, cask or the way that you have run things, I do not know. One possibility, for example, is that you ran "cask install" with a different emacs from the one referenced here.

Can you run `make test` rather than `make just-test` and show the output of that?

**Comment by dunn** [comment]
`make test` works fine on a fresh clone of this repository, so there must have been something funny with my environment.  Sorry for the false alarm!

**Comment by phillord** [comment]
No worries, glad to hear its fixed.
